# Generated by Django 4.2.5 on 2023-10-09 21:28

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='pics_2',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.user_directory_path, verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='pics_3',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.user_directory_path, verbose_name='Photo 3'),
        ),
    ]
