# Generated by Django 4.2.5 on 2023-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_garment_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
