# Generated by Django 4.2.5 on 2023-10-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_garment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='year',
            field=models.DateField(blank=True, verbose_name='Année'),
        ),
    ]
