# Generated by Django 4.2.5 on 2023-10-11 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_garment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='reference',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='Référence'),
        ),
    ]
