# Generated by Django 4.2.5 on 2023-10-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_garment_cart_garments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
