# Generated by Django 4.2.5 on 2023-10-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_cart_garments_order_cart_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='purchased',
        ),
    ]
