# Generated by Django 4.2.5 on 2023-10-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_garment_buyer_remove_garment_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='purchased',
            field=models.BooleanField(default=False, verbose_name='Acheté'),
        ),
    ]
