# Generated by Django 4.2.5 on 2023-10-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_garment_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='purchased',
            new_name='activate',
        ),
    ]
