# Generated by Django 4.2.5 on 2023-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_purchased_garment_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Activé'),
        ),
    ]
