# Generated by Django 4.2.5 on 2023-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_garment_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='description',
            field=models.CharField(help_text='50 mots max', max_length=50, verbose_name='Description'),
        ),
    ]
