# Generated by Django 4.2.5 on 2023-10-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_alter_garment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Acheteur'),
        ),
        migrations.AddField(
            model_name='order',
            name='validation',
            field=models.BooleanField(default=False, help_text='Validation de la plateforme', verbose_name='Validation du deal'),
        ),
    ]
