# Generated by Django 4.2.5 on 2023-10-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_garment_buyer_order_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='buyer',
        ),
    ]
