# Generated by Django 4.2.5 on 2023-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_garment_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='validation',
            field=models.BooleanField(default=False, verbose_name='Validation du deal'),
        ),
    ]
