# Generated by Django 4.2.5 on 2023-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_order_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('ch', 'Chaussures'), ('pa', 'Pantalons'), ('ha', 'Hauts')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
