# Generated by Django 4.2.5 on 2023-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0002_message_date_ticket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Objet'),
            preserve_default=False,
        ),
    ]
