# Generated by Django 4.2.5 on 2023-10-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exchanger_favorite_color_exchanger_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanger',
            name='type',
            field=models.CharField(choices=[('h', 'Homme'), ('f', 'Femme'), ('nr', 'Non renseigné')], max_length=10, verbose_name='Sexe'),
        ),
    ]
