# Generated by Django 4.2.5 on 2023-10-05 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_exchangeradresses_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeradresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
